name: flu_wake_lock
description: >-2
  Plugin that allows you to keep the device screen awake, i.e. prevent the screen from sleeping on
  Android and iOS.
version: 0.0.2
homepage: https://github.com/dualskana/flu_wake_lock
repository: https://github.com/dualskana/flu_wake_lock

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flu_wake_lock
        pluginClass: FluWakeLockPlugin
      ios:
        pluginClass: FluWakeLockPlugin